[package]
name = "rxmodb"
version = "0.2.0"
description = "RxMoDb is a Motoko Database using Vector for its main storage and BTree for indexes"
repository = "https://github.com/infu/rxmodb"

[dependencies]
base = "0.11.1"
rxmo = "0.2.0"
stableheapbtreemap = "1.5.0"
vector = "0.3.1"
test = "1.2.0"